#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

function parseArgs(argv) {
  const options = {
    root: null,
    format: "text",
    noReports: false,
    write: false,
    packageName: null,
    roots: [],
  };

  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];
    if (arg === "--root") {
      options.root = argv[i + 1];
      i += 2;
    } else if (arg === "--format") {
      options.format = argv[i + 1] ?? "text";
      i += 2;
    } else if (arg === "--no-reports") {
      options.noReports = true;
      i += 1;
    } else if (arg === "--write") {
      options.write = true;
      i += 1;
    } else if (arg === "--check") {
      options.write = false;
      i += 1;
    } else if (arg === "--package") {
      options.packageName = argv[i + 1];
      i += 2;
    } else if (arg.startsWith("--")) {
      throw new Error(`Unknown option: ${arg}`);
    } else {
      options.roots.push(arg);
      i += 1;
    }
  }

  if (!["text", "json"].includes(options.format)) {
    throw new Error("--format must be text or json");
  }

  return options;
}

const OPTIONS = parseArgs(process.argv.slice(2));
const REPO_ROOT = findRepoRoot(OPTIONS.root ? path.resolve(OPTIONS.root) : process.cwd());
const TOOLING_REPORT_DIR = path.join(REPO_ROOT, "reports", "tooling", "generate-package-readmes");
const TOOL_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TOOL_PACKAGE_PATH = path.join(TOOL_ROOT, "package.json");

function findRepoRoot(startDir) {
  let dir = path.resolve(startDir);
  while (true) {
    if (fs.existsSync(path.join(dir, "docs", "schemas", "package-json-architecture.schema.json"))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      return path.resolve(startDir);
    }
    dir = parent;
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function isReadmeFixtureDirectory(directoryPath) {
  const parts = directoryPath.split(path.sep);
  return parts.includes("tests") && parts.includes("fixtures");
}

function walkReadmes(current, results, ignored, explicitFixtureScan) {
  const stat = fs.statSync(current);
  if (stat.isDirectory()) {
    const base = path.basename(current);
    if (ignored.has(base)) return;
    if (!explicitFixtureScan && isReadmeFixtureDirectory(current)) return;
    for (const entry of fs.readdirSync(current)) {
      walkReadmes(path.join(current, entry), results, ignored, explicitFixtureScan);
    }
    return;
  }
  if (path.basename(current) === "package.json") {
    results.push(current);
  }
}

function listPackageJsonFiles(searchRoots) {
  const ignored = new Set(["node_modules", ".git", "dist", "build", "coverage", "reports"]);
  const results = [];
  const explicitFixtureScan = searchRoots.some((root) => root.split(/[\\/]/).includes("fixtures"));

  for (const root of searchRoots) {
    const absoluteRoot = path.resolve(REPO_ROOT, root);
    if (!fs.existsSync(absoluteRoot)) {
      continue;
    }
    walkReadmes(absoluteRoot, results, ignored, explicitFixtureScan);
  }

  return [...new Set(results)].sort();
}

function listItems(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "- None recorded.";
  }
  return items.map((item) => `- ${item}`).join("\n");
}

function codeList(items) {
  if (!Array.isArray(items) || items.length === 0) {
    return "None";
  }
  return items.join("\n");
}

function renderReadme(packageJson) {
  const a = packageJson.architecture;
  const component = a.component;
  const lifecycle = a.lifecycle;
  const governance = a.governance;
  const runtime = a.runtime;
  const boundaries = a.boundaries;
  const relations = a.relations;
  const readme = a.readme;

  return `<!-- GENERATED BY tools/architecture/generate-package-readmes. DO NOT EDIT OUTSIDE APPROVED EXTENSION SECTIONS. -->

# ${packageJson.name}

${readme.summary}

## Package identity

\`\`\`text
Name: ${packageJson.name}
Version: ${packageJson.version}
Component: ${component.name}
Type: ${component.type}
System: ${component.system}
Domain: ${component.domain}
Bounded context: ${component.boundedContext}
Owner: ${component.owner}
\`\`\`

## Lifecycle

\`\`\`text
Stage: ${lifecycle.stage}
Role: ${lifecycle.role}
Class: ${lifecycle.class}
Catalog lifecycle: ${lifecycle.catalogLifecycle}
Visibility: ${lifecycle.visibility}
Support level: ${lifecycle.supportLevel}
Review cadence: ${lifecycle.reviewCadence}
\`\`\`

## Ownership

\`\`\`text
Owner: ${component.owner}
Change control: ${governance.changeControl}
Promotion eligible: ${governance.promotionEligible}
Semver policy: ${governance.semverPolicy}
\`\`\`

## Responsibilities

${listItems(readme.responsibilities)}

## Non-responsibilities

${listItems(readme.nonResponsibilities)}

## Public exports and usage

\`\`\`text
Public exports only: ${boundaries.publicExportsOnly}
Deep imports allowed: ${boundaries.deepImportsAllowed}
\`\`\`

${listItems(readme.usage)}

## Boundaries

### Allowed consumers

\`\`\`text
${codeList(boundaries.allowedConsumers)}
\`\`\`

### Forbidden consumers

\`\`\`text
${codeList(boundaries.forbiddenConsumers)}
\`\`\`

## Runtime and environments

\`\`\`text
Production: ${runtime.production}
Test only: ${runtime.testOnly}
Service name: ${runtime.serviceName}
Service namespace: ${runtime.serviceNamespace}
Deployment environments:
${codeList(runtime.deploymentEnvironments)}
\`\`\`

## Relations

### Depends on

\`\`\`text
${codeList(relations.dependsOn)}
\`\`\`

### Provides APIs

\`\`\`text
${codeList(relations.providesApis)}
\`\`\`

### Consumes APIs

\`\`\`text
${codeList(relations.consumesApis)}
\`\`\`

## Operational notes

${listItems(readme.operationalNotes)}

## Governance

\`\`\`text
Decision refs:
${codeList(governance.decisionRefs)}
\`\`\`

## Validation

Run architecture tooling from the repository root.

\`\`\`text
node tools/architecture/orchestrator/src/index.mjs validate
\`\`\`

## Extension notes

Manual notes may be added only inside approved extension sections if repository policy allows it.

<!-- BEGIN MANUAL EXTENSION -->

<!-- END MANUAL EXTENSION -->
`;
}

const REQUIRED_README_HEADINGS = [
  "# ",
  "## Package identity",
  "## Lifecycle",
  "## Ownership",
  "## Responsibilities",
  "## Non-responsibilities",
  "## Public exports and usage",
  "## Boundaries",
  "## Runtime and environments",
  "## Relations",
  "## Operational notes",
  "## Governance",
  "## Validation",
  "## Extension notes",
];

const GENERATED_NOTICE =
  "<!-- GENERATED BY tools/architecture/generate-package-readmes. DO NOT EDIT OUTSIDE APPROVED EXTENSION SECTIONS. -->";
const MANUAL_BEGIN = "<!-- BEGIN MANUAL EXTENSION -->";
const MANUAL_END = "<!-- END MANUAL EXTENSION -->";

function validateReadmeStructure(content) {
  const errors = [];

  if (!content.startsWith(GENERATED_NOTICE)) {
    errors.push("README must start with generated notice");
  }

  for (const heading of REQUIRED_README_HEADINGS) {
    if (!content.includes(heading)) {
      errors.push(`README missing required heading: ${heading}`);
    }
  }

  const manualBeginIndex = content.indexOf(MANUAL_BEGIN);
  const manualEndIndex = content.indexOf(MANUAL_END);

  if (manualBeginIndex === -1) {
    errors.push("README missing manual extension begin marker");
  }

  if (manualEndIndex === -1) {
    errors.push("README missing manual extension end marker");
  }

  if (manualBeginIndex !== -1 && manualEndIndex !== -1 && manualBeginIndex > manualEndIndex) {
    errors.push("README manual extension markers are out of order");
  }

  return errors;
}

function stripManualExtension(content) {
  const manualBeginIndex = content.indexOf(MANUAL_BEGIN);
  const manualEndIndex = content.indexOf(MANUAL_END);

  if (manualBeginIndex === -1 || manualEndIndex === -1 || manualBeginIndex > manualEndIndex) {
    return content;
  }

  return `${content.slice(0, manualBeginIndex + MANUAL_BEGIN.length)}\n\n${content.slice(manualEndIndex)}`;
}

function preserveManualExtension(expected, current) {
  if (current === null) {
    return expected;
  }

  const currentBeginIndex = current.indexOf(MANUAL_BEGIN);
  const currentEndIndex = current.indexOf(MANUAL_END);
  const expectedBeginIndex = expected.indexOf(MANUAL_BEGIN);
  const expectedEndIndex = expected.indexOf(MANUAL_END);

  if (
    currentBeginIndex === -1 ||
    currentEndIndex === -1 ||
    expectedBeginIndex === -1 ||
    expectedEndIndex === -1 ||
    currentBeginIndex > currentEndIndex ||
    expectedBeginIndex > expectedEndIndex
  ) {
    return expected;
  }

  const manualContent = current.slice(currentBeginIndex + MANUAL_BEGIN.length, currentEndIndex);

  return `${expected.slice(0, expectedBeginIndex + MANUAL_BEGIN.length)}${manualContent}${expected.slice(expectedEndIndex)}`;
}

function detectManualEditsOutsideExtension(current, expected) {
  if (current === null) {
    return [];
  }

  const normalizedCurrent = stripManualExtension(current);
  const normalizedExpected = stripManualExtension(expected);

  if (normalizedCurrent !== normalizedExpected) {
    return ["README contains manual edits outside approved extension markers"];
  }

  return [];
}

function resolvePackageStatus(fresh) {
  if (fresh) return "fresh";
  if (OPTIONS.write) return "written";
  return "stale";
}

function checkPackageReadme(packageJson, packageFile, readmePath) {
  const expected = renderReadme(packageJson);
  let current = null;
  try {
    current = fs.readFileSync(readmePath, "utf8"); // read directly; avoids existsSync TOCTOU
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }
  const expectedStructureErrors = validateReadmeStructure(expected);
  const currentStructureErrors =
    current === null ? ["README.md is missing"] : validateReadmeStructure(current);
  const manualEditErrors = detectManualEditsOutsideExtension(current, expected);
  const structureErrors =
    current === null ? currentStructureErrors : [...currentStructureErrors, ...manualEditErrors];
  const generatedSectionsFresh =
    current !== null && stripManualExtension(current) === stripManualExtension(expected);
  const fresh =
    generatedSectionsFresh && structureErrors.length === 0 && expectedStructureErrors.length === 0;
  const output = preserveManualExtension(expected, current);

  if (OPTIONS.write && !fresh) {
    fs.writeFileSync(readmePath, output, "utf8");
  }

  return {
    packageName: packageJson.name ?? "(unknown)",
    packagePath: path.relative(REPO_ROOT, packageFile),
    readmePath: path.relative(REPO_ROOT, readmePath),
    status: resolvePackageStatus(fresh),
    changed: !fresh,
    structureErrors: OPTIONS.write
      ? validateReadmeStructure(output)
      : [...expectedStructureErrors, ...structureErrors],
    manualExtensionPreserved: OPTIONS.write && current !== null && output !== expected,
  };
}

function processPackage(packageFile) {
  const packageJson = readJson(packageFile);
  const packageDir = path.dirname(packageFile);
  const readmePath = path.join(packageDir, "README.md");

  if (!packageJson.architecture?.readme?.generated) {
    return {
      packageName: packageJson.name ?? "(unknown)",
      packagePath: path.relative(REPO_ROOT, packageFile),
      readmePath: path.relative(REPO_ROOT, readmePath),
      status: "skipped",
      reason: "architecture.readme.generated is not true",
    };
  }

  if (OPTIONS.packageName && packageJson.name !== OPTIONS.packageName) {
    return {
      packageName: packageJson.name ?? "(unknown)",
      packagePath: path.relative(REPO_ROOT, packageFile),
      readmePath: path.relative(REPO_ROOT, readmePath),
      status: "skipped",
      reason: "package filter",
    };
  }

  return checkPackageReadme(packageJson, packageFile, readmePath);
}

function writeSelfEvidence({ startedAt, finishedAt, results, exitCode, roots }) {
  if (OPTIONS.noReports) {
    return null;
  }

  fs.mkdirSync(TOOLING_REPORT_DIR, { recursive: true });
  const safeTimestamp = finishedAt.replace(/[:.]/g, "-");
  const evidencePath = path.join(TOOLING_REPORT_DIR, `${safeTimestamp}-run.json`);
  const evidence = {
    toolName: "generate-package-readmes",
    toolVersion: readJson(TOOL_PACKAGE_PATH).version ?? "0.0.0",
    command: [
      "node",
      "tools/architecture/generate-package-readmes/src/index.mjs",
      ...process.argv.slice(2),
    ],
    mode: OPTIONS.write ? "write" : "check",
    root: REPO_ROOT,
    startedAt,
    finishedAt,
    durationMs: new Date(finishedAt).getTime() - new Date(startedAt).getTime(),
    inputRoots: roots,
    outputPaths: results.filter((r) => r.status === "written").map((r) => r.readmePath),
    rulesEvaluated: [
      "package readme generation from package.json architecture metadata",
      "check mode reports stale README without writing",
      "write mode writes only package-local README.md",
      "generated README required heading validation",
      "manual edits outside extension markers are rejected",
      "manual content inside extension markers is preserved on write",
    ],
    checksPassed: results.filter((r) => ["fresh", "written", "skipped"].includes(r.status)).length,
    checksFailed: results.filter((r) => r.status === "stale").length,
    warnings: [],
    errors: results
      .filter((r) => r.status === "stale")
      .flatMap((r) => {
        const errors = r.structureErrors?.length
          ? r.structureErrors
          : ["README.md is stale or missing"];
        return errors.map((message) => ({
          packageName: r.packageName,
          packagePath: r.packagePath,
          message,
        }));
      }),
    dependencySteps: [],
    gitTreatment: "package README commit policy governed by ADR-0007 and ADR-0008",
    exitCode,
  };
  fs.writeFileSync(evidencePath, `${JSON.stringify(evidence, null, 2)}\n`, "utf8");
  return evidencePath;
}

function main() {
  const startedAt = new Date().toISOString();
  const roots =
    OPTIONS.roots.length > 0 ? OPTIONS.roots : ["apps", "packages", "tools/architecture"];
  const packageFiles = listPackageJsonFiles(roots);
  const results = packageFiles.map(processPackage);
  const stale = results.filter((result) => result.status === "stale").length;
  const exitCode = stale > 0 ? 1 : 0;
  const finishedAt = new Date().toISOString();
  const selfEvidencePath = writeSelfEvidence({ startedAt, finishedAt, results, exitCode, roots });

  const summary = {
    toolName: "generate-package-readmes",
    mode: OPTIONS.write ? "write" : "check",
    totalPackages: results.length,
    fresh: results.filter((r) => r.status === "fresh").length,
    written: results.filter((r) => r.status === "written").length,
    stale,
    skipped: results.filter((r) => r.status === "skipped").length,
    results,
    selfEvidencePath: selfEvidencePath ? path.relative(REPO_ROOT, selfEvidencePath) : null,
    exitCode,
  };

  if (OPTIONS.format === "json") {
    console.log(JSON.stringify(summary, null, 2));
  } else {
    console.log(`Generated package README check: ${OPTIONS.write ? "write" : "check"}`);
    console.log(`Packages: ${summary.totalPackages}`);
    console.log(`Fresh: ${summary.fresh}`);
    console.log(`Written: ${summary.written}`);
    console.log(`Stale: ${summary.stale}`);
    console.log(`Skipped: ${summary.skipped}`);
    if (selfEvidencePath) {
      console.log(`Self-evidence: ${path.relative(REPO_ROOT, selfEvidencePath)}`);
    }
  }

  process.exit(exitCode);
}

try {
  main();
} catch (error) {
  if (OPTIONS.format === "json") {
    console.log(
      JSON.stringify(
        { toolName: "generate-package-readmes", error: error.message, exitCode: 1 },
        null,
        2
      )
    );
  } else {
    console.error(error.message);
  }
  process.exit(1);
}
