#!/usr/bin/env node
// Governance validator + renderer for the Universal Service Foundation (ADR-ACT-0237).
//
// Source of truth: docs/evidence/platform/universal-service-foundation-registry.json (data only).
// Human view:      docs/evidence/platform/universal-service-foundation-matrix.md
//
// This validator enforces the Phase-8 invariants requested for the matrix/registry. It does NOT
// validate any unimplemented service — only that the planning artifact is internally honest:
//
//   1. every capability row has a status from the controlled vocabulary;
//   2. every row has a build/compose/adapter/defer/reject decision;
//   3. every row has an environment classification from the controlled vocabulary;
//   4. every shared (`shared*`) service carries leakage/isolation notes;
//   5. every production candidate (build/compose/adapter, not forbidden-in-production / mock-only)
//      names a local free development path (no "none"/"paid"), unless it is production-external;
//   6. no capability marked `delivered`/`locally proven` lacks a route/contract OR proof/evidence ref;
//   7. every `adr` reference resolves to a docs/adr/NNNN-*.md file on disk;
//   8. every `actionRegister` row referenced is present in docs/adr/ACTION-REGISTER.md AND linked
//      from the matrix markdown, and every capability key appears in the matrix markdown.
//
// `--render` rewrites the generated tables block in the matrix markdown from the registry, so the
// two never drift. Exit 0 on success, 1 on any problem.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../../..");

const REGISTRY_REL = "docs/evidence/platform/universal-service-foundation-registry.json";
const MATRIX_REL = "docs/evidence/platform/universal-service-foundation-matrix.md";
const TABLE_START =
  "<!-- USF-TABLE:START — generated by tools/architecture/validate-universal-foundation; do not edit by hand -->";
const TABLE_END = "<!-- USF-TABLE:END -->";

const DOMAIN_TITLES = {
  "identity-access": "Identity and access",
  authentication: "Authentication",
  configuration: "Configuration and tenant self-management",
  "billing-entitlements": "Billing, metering, and entitlements",
  "data-platform": "Data platform",
  search: "Search",
  storage: "Storage",
  "events-queues-workflows": "Events, queues, and workflows",
  "compute-runtime": "Compute and application runtime",
  "observability-ops": "Observability and operations",
  "security-governance": "Security and governance",
  "developer-platform": "Developer platform",
  "support-admin": "Support and enterprise administration",
  "foundation-cross-cutting": "Foundation (cross-cutting governance)",
};

export function loadRegistry(repoRoot = REPO_ROOT) {
  return JSON.parse(fs.readFileSync(path.join(repoRoot, REGISTRY_REL), "utf8"));
}

export function adrNumbersOnDisk(repoRoot = REPO_ROOT) {
  const dir = path.join(repoRoot, "docs", "adr");
  const nums = new Set();
  for (const f of fs.readdirSync(dir)) {
    const m = /^(\d{4})-.*\.md$/.exec(f);
    if (m) nums.add(Number(m[1]));
  }
  return nums;
}

function isShared(cap) {
  return (
    /shared/i.test(cap.sharedPerEnv ?? "") || cap.environmentModel === "shared-cross-environment"
  );
}

function hasIsolationNotes(cap) {
  const blob =
    `${cap.tenantIsolation ?? ""} ${cap.dataIsolation ?? ""} ${cap.notes ?? ""}`.toLowerCase();
  return /(isolat|tag|leak|partition|scope|access control|retention|boundary|forbidden)/.test(blob);
}

function isProductionCandidate(cap) {
  if (!["build", "compose", "adapter"].includes(cap.decision)) return false;
  if (
    ["mock-only", "forbidden-in-production", "production-external", "not-applicable"].includes(
      cap.environmentModel
    )
  )
    return false;
  return true;
}

function hasLocalFreePath(cap) {
  const c = (cap.localFreeCandidate ?? "").trim().toLowerCase();
  if (!c) return false;
  if (c === "none" || c === "n/a") return false;
  if (/\bpaid\b/.test(c) && !/oss|composed|built-in|local/.test(c)) return false;
  return true;
}

function isDeliveredish(cap) {
  return cap.status === "delivered" || cap.status === "locally proven";
}

function hasRouteOrProof(cap) {
  const route = (cap.bffContract ?? "").trim().toLowerCase();
  const proof = (cap.proof ?? "").trim().toLowerCase();
  const routeOk = route && !/^missing/.test(route) && route !== "n/a";
  const proofOk = proof && !/not-yet-proven|^missing|^blocked/.test(proof);
  // governance/decision artifacts legitimately have no BFF route; a proof/evidence ref suffices.
  return routeOk || proofOk;
}

export function validate(repoRoot = REPO_ROOT) {
  const problems = [];
  const reg = loadRegistry(repoRoot);
  const statusVocab = new Set(reg.statusVocabulary);
  const decisionVocab = new Set(reg.decisionVocabulary);
  const envVocab = new Set(reg.environmentModelVocabulary);
  const onDisk = adrNumbersOnDisk(repoRoot);

  const matrixPath = path.join(repoRoot, MATRIX_REL);
  const matrixText = fs.existsSync(matrixPath) ? fs.readFileSync(matrixPath, "utf8") : "";
  const registerText = fs.readFileSync(
    path.join(repoRoot, "docs", "adr", "ACTION-REGISTER.md"),
    "utf8"
  );

  const seenKeys = new Set();
  const referencedActs = new Set();

  for (const cap of reg.capabilities) {
    const id = cap.capability ?? "(missing key)";
    if (!cap.capability) problems.push("a capability row is missing its `capability` key");
    if (seenKeys.has(id)) problems.push(`duplicate capability key: ${id}`);
    seenKeys.add(id);

    // 1. status
    if (!statusVocab.has(cap.status))
      problems.push(`${id}: status "${cap.status}" not in controlled vocabulary`);
    // 2. decision
    if (!decisionVocab.has(cap.decision))
      problems.push(`${id}: decision "${cap.decision}" not in controlled vocabulary`);
    // 3. environment classification
    if (!envVocab.has(cap.environmentModel))
      problems.push(
        `${id}: environmentModel "${cap.environmentModel}" not in controlled vocabulary`
      );
    // 4. shared services carry isolation notes
    if (isShared(cap) && !hasIsolationNotes(cap))
      problems.push(`${id}: shared service must carry leakage/isolation notes`);
    // 5. production candidate has a local free path
    if (isProductionCandidate(cap) && !hasLocalFreePath(cap))
      problems.push(
        `${id}: production candidate must name a local free development path (got "${cap.localFreeCandidate}")`
      );
    // 6. delivered requires route or proof
    if (isDeliveredish(cap) && !hasRouteOrProof(cap))
      problems.push(
        `${id}: status "${cap.status}" requires a BFF/route contract or a proof/evidence reference`
      );
    // 7. ADR references resolve to files
    for (const m of `${cap.adr ?? ""}`.matchAll(/\bADR-(\d{4})\b/g)) {
      const n = Number(m[1]);
      if (!onDisk.has(n))
        problems.push(`${id}: references ADR-${m[1]} but docs/adr/ has no matching file`);
    }
    // 8a. ADR-ACT present in register + linked from matrix
    for (const m of `${cap.actionRegister ?? ""}`.matchAll(/\bADR-ACT-(\d{4})\b/g)) {
      const act = `ADR-ACT-${m[1]}`;
      referencedActs.add(act);
      if (!registerText.includes(act))
        problems.push(`${id}: actionRegister ${act} is not present in ACTION-REGISTER.md`);
      if (matrixText && !matrixText.includes(act))
        problems.push(`${id}: actionRegister ${act} is not linked from the matrix markdown`);
    }
    // 8b. every capability appears in the matrix markdown
    if (matrixText && cap.capability && !matrixText.includes(cap.capability)) {
      problems.push(`${id}: capability key does not appear in the matrix markdown (run --render)`);
    }
  }

  return {
    ok: problems.length === 0,
    problems,
    count: reg.capabilities.length,
    referencedActs: [...referencedActs].sort(),
  };
}

function esc(v) {
  return String(v ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

export function renderTables(repoRoot = REPO_ROOT) {
  const reg = loadRegistry(repoRoot);
  const byDomain = new Map();
  for (const d of reg.domains) byDomain.set(d, []);
  for (const cap of reg.capabilities) {
    if (!byDomain.has(cap.domain)) byDomain.set(cap.domain, []);
    byDomain.get(cap.domain).push(cap);
  }

  const out = [];
  out.push(
    `<!-- Generated from ${REGISTRY_REL} on ${reg.date}. ${reg.capabilities.length} capability rows. -->`
  );
  out.push("");
  for (const [domain, caps] of byDomain) {
    if (!caps.length) continue;
    out.push(`### ${DOMAIN_TITLES[domain] ?? domain}`);
    out.push("");
    // Decision table
    out.push(
      "| Capability | Status | Purpose | Compose / provider | Decision | Local free candidate | Environment model | Shared/per-env | Priority | Size | Risk |"
    );
    out.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
    for (const c of caps) {
      out.push(
        `| \`${esc(c.capability)}\` | ${esc(c.status)} | ${esc(c.purpose)} | ${esc(c.composeSupport)} | ${esc(c.decision)} | ${esc(c.localFreeCandidate)} | ${esc(c.environmentModel)} | ${esc(c.sharedPerEnv)} | ${esc(c.priority)} | ${esc(c.size)} | ${esc(c.risk)} |`
      );
    }
    out.push("");
    // Governance / isolation table
    out.push(
      "| Capability | Tenant isolation | Data isolation | Permission | Audit events | Readiness model | BFF contract | Admin UI | Self-service UI | Proof | Production blockers | ADR | ADR-ACT | Notes |"
    );
    out.push(
      "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    );
    for (const c of caps) {
      out.push(
        `| \`${esc(c.capability)}\` | ${esc(c.tenantIsolation)} | ${esc(c.dataIsolation)} | ${esc(c.permissionModel)} | ${esc(c.auditEvents)} | ${esc(c.readinessModel)} | ${esc(c.bffContract)} | ${esc(c.adminUi)} | ${esc(c.selfServiceUi)} | ${esc(c.proof)} | ${esc(c.productionBlockers)} | ${esc(c.adr)} | ${esc(c.actionRegister)} | ${esc(c.notes)} |`
      );
    }
    out.push("");
  }
  return out.join("\n");
}

export function render(repoRoot = REPO_ROOT) {
  const matrixPath = path.join(repoRoot, MATRIX_REL);
  const text = fs.readFileSync(matrixPath, "utf8");
  const startIdx = text.indexOf(TABLE_START);
  const endIdx = text.indexOf(TABLE_END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`matrix markdown is missing the ${TABLE_START} / ${TABLE_END} markers`);
  }
  const before = text.slice(0, startIdx + TABLE_START.length);
  const after = text.slice(endIdx);
  const next = `${before}\n\n${renderTables(repoRoot)}\n${after}`;
  fs.writeFileSync(matrixPath, next);
  return next;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const mode = process.argv[2];
  if (mode === "--render") {
    render();
    console.log("[validate-universal-foundation] rendered matrix tables from registry.");
  }
  const result = validate();
  if (result.ok) {
    console.log(
      `[validate-universal-foundation] OK — ${result.count} capabilities; ADR-ACT linked: ${result.referencedActs.join(", ")}.`
    );
    process.exit(0);
  }
  console.error("[validate-universal-foundation] problems:");
  for (const p of result.problems) console.error(`  - ${p}`);
  process.exit(1);
}
