#!/usr/bin/env node
// Governance validator + renderer for the Universal Service Foundation (ADR-ACT-0237).
//
// Source of truth: docs/evidence/platform/universal-service-foundation-registry.json (data only).
// Human view:      docs/evidence/platform/universal-service-foundation-matrix.md
//
// This validator enforces the Phase-8 invariants requested for the matrix/registry. It does NOT
// validate any unimplemented service — only that the planning artifact is internally honest:
//
//   1. every capability row has a status from the controlled vocabulary;
//   2. every row has a build/compose/adapter/defer/reject decision;
//   3. every row has an environment classification from the controlled vocabulary;
//   4. every shared (`shared*`) service carries leakage/isolation notes;
//   5. every production candidate (build/compose/adapter, not forbidden-in-production / mock-only)
//      names a local free development path (no "none"/"paid"), unless it is production-external;
//   6. no capability marked `delivered`/`locally proven` lacks a route/contract OR proof/evidence ref;
//   7. every `adr` reference resolves to a docs/adr/NNNN-*.md file on disk;
//   8. every `actionRegister` row referenced is present in docs/adr/ACTION-REGISTER.md AND linked
//      from the matrix markdown, and every capability key appears in the matrix markdown.
//
// `--render` rewrites the generated tables block in the matrix markdown from the registry, so the
// two never drift. Exit 0 on success, 1 on any problem.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../../../..");

const REGISTRY_REL = "docs/evidence/platform/universal-service-foundation-registry.json";
const MATRIX_REL = "docs/evidence/platform/universal-service-foundation-matrix.md";
const TABLE_START =
  "<!-- USF-TABLE:START — generated by tools/architecture/validate-universal-foundation; do not edit by hand -->";
const TABLE_END = "<!-- USF-TABLE:END -->";

// Source surfaces used by the honesty checks (Workstream F hardening, ADR-ACT-0252).
const ROUTES_REL = "apps/platform-api/src/server/routes.ts";
const ADMIN_ROUTES_DIR_REL = "apps/react-enterprise-app/src/routes/admin";
const PKG_REL = "package.json";
const COMPOSE_REL = "compose.yaml";
// Services that must never run in production and must therefore stay behind a Compose profile.
const FORBIDDEN_COMPOSE_SERVICES = ["localstack", "wiremock", "mock-oidc"];

const DOMAIN_TITLES = {
  "identity-access": "Identity and access",
  authentication: "Authentication",
  configuration: "Configuration and tenant self-management",
  "billing-entitlements": "Billing, metering, and entitlements",
  "data-platform": "Data platform",
  search: "Search",
  storage: "Storage",
  "events-queues-workflows": "Events, queues, and workflows",
  "compute-runtime": "Compute and application runtime",
  "observability-ops": "Observability and operations",
  "security-governance": "Security and governance",
  "developer-platform": "Developer platform",
  "support-admin": "Support and enterprise administration",
  "foundation-cross-cutting": "Foundation (cross-cutting governance)",
};

export function loadRegistry(repoRoot = REPO_ROOT) {
  return JSON.parse(fs.readFileSync(path.join(repoRoot, REGISTRY_REL), "utf8"));
}

export function adrNumbersOnDisk(repoRoot = REPO_ROOT) {
  const dir = path.join(repoRoot, "docs", "adr");
  const nums = new Set();
  for (const f of fs.readdirSync(dir)) {
    const m = /^(\d{4})-.*\.md$/.exec(f);
    if (m) nums.add(Number(m[1]));
  }
  return nums;
}

function readTextSafe(repoRoot, rel) {
  const p = path.join(repoRoot, rel);
  return fs.existsSync(p) ? fs.readFileSync(p, "utf8") : "";
}

export function packageScripts(repoRoot = REPO_ROOT) {
  try {
    return JSON.parse(readTextSafe(repoRoot, PKG_REL)).scripts ?? {};
  } catch {
    return {};
  }
}

export function adminRouteSet(repoRoot = REPO_ROOT) {
  const set = new Set(["/admin"]);
  const dir = path.join(repoRoot, ADMIN_ROUTES_DIR_REL);
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) {
      const m = /^(.*)\.tsx$/.exec(f);
      if (m && m[1] !== "layout" && m[1] !== "index") set.add(`/admin/${m[1]}`);
    }
  }
  return set;
}

// Read the one-line status of an ADR (## Status followed by the value). Returns "" if not found.
export function adrStatus(repoRoot, num) {
  const dir = path.join(repoRoot, "docs", "adr");
  const file = fs.readdirSync(dir).find((f) => f.startsWith(`${num}-`) && f.endsWith(".md"));
  if (!file) return "";
  const text = fs.readFileSync(path.join(dir, file), "utf8");
  const m = /##\s*Status\s*\n+\s*([^\n]+)/.exec(text);
  return m ? m[1].trim() : "";
}

// An ADR is ready to back implementation if it is Accepted or explicitly marked implementation-ready.
export function adrImplementationReady(repoRoot, ref) {
  const num = /(\d{4})/.exec(`${ref}`)?.[1];
  if (!num) return false;
  const status = adrStatus(repoRoot, num);
  return /accepted/i.test(status) || /implementation-ready/i.test(status);
}

// Capability statuses that represent concrete delivery progress (i.e. "implementation started").
const ADVANCED_STATUSES = new Set(["delivered", "locally proven", "ui-only", "compose-only"]);

// Tokens matching a path prefix (e.g. /api/, /admin/), trimmed of trailing wildcards/punctuation.
function pathTokens(value, prefix) {
  const re = new RegExp(`${prefix.replace(/\//g, "\\/")}[a-z0-9/_-]+`, "g");
  return [...`${value ?? ""}`.matchAll(re)].map((m) => m[0]);
}

function proofTokens(value) {
  return [...`${value ?? ""}`.matchAll(/\bproof:[a-z0-9-]+/g)].map((m) => m[0]);
}

// A Compose service is profile-gated if a `profiles:` line appears within its block.
function composeServiceIsGated(composeText, service) {
  const lines = composeText.split("\n");
  let inBlock = false;
  for (const line of lines) {
    if (/^ {2}[a-zA-Z0-9_.-]+:\s*$/.test(line)) {
      inBlock = new RegExp(`^ {2}${service}:\\s*$`).test(line);
      continue;
    }
    if (inBlock && /^\s+profiles:\s*\[/.test(line)) return true;
  }
  return false;
}

function isShared(cap) {
  return (
    /shared/i.test(cap.sharedPerEnv ?? "") || cap.environmentModel === "shared-cross-environment"
  );
}

function hasIsolationNotes(cap) {
  const blob =
    `${cap.tenantIsolation ?? ""} ${cap.dataIsolation ?? ""} ${cap.notes ?? ""}`.toLowerCase();
  return /(isolat|tag|leak|partition|scope|access control|retention|boundary|forbidden)/.test(blob);
}

function isProductionCandidate(cap) {
  if (!["build", "compose", "adapter"].includes(cap.decision)) return false;
  if (
    ["mock-only", "forbidden-in-production", "production-external", "not-applicable"].includes(
      cap.environmentModel
    )
  )
    return false;
  return true;
}

function hasLocalFreePath(cap) {
  const c = (cap.localFreeCandidate ?? "").trim().toLowerCase();
  if (!c) return false;
  if (c === "none" || c === "n/a") return false;
  if (/\bpaid\b/.test(c) && !/oss|composed|built-in|local/.test(c)) return false;
  return true;
}

function isDeliveredish(cap) {
  return cap.status === "delivered" || cap.status === "locally proven";
}

function hasRouteOrProof(cap) {
  const route = (cap.bffContract ?? "").trim().toLowerCase();
  const proof = (cap.proof ?? "").trim().toLowerCase();
  const routeOk = route && !/^missing/.test(route) && route !== "n/a";
  const proofOk = proof && !/not-yet-proven|^missing|^blocked/.test(proof);
  // governance/decision artifacts legitimately have no BFF route; a proof/evidence ref suffices.
  return routeOk || proofOk;
}

// Pure validation of the delivery spine (phase assignment + dependency graph). `capabilityKeys` is
// the Set of known capability keys. Returns an array of problem strings. Exported for unit testing.
export function validateDelivery(delivery, capabilityKeys) {
  const problems = [];
  if (!delivery) {
    problems.push("registry is missing the `delivery` block (phase + dependency graph)");
    return problems;
  }
  const keys = capabilityKeys instanceof Set ? capabilityKeys : new Set(capabilityKeys ?? []);
  const phaseOrder = new Set(delivery.phaseOrder ?? []);
  const rows = delivery.dependencies ?? [];
  const byCap = new Map();
  for (const row of rows) {
    if (byCap.has(row.capability))
      problems.push(`delivery: duplicate dependency row for ${row.capability}`);
    byCap.set(row.capability, row);
  }
  // every capability is covered exactly once
  for (const k of keys) {
    if (!byCap.has(k)) problems.push(`delivery: capability ${k} has no dependency/phase row`);
  }
  for (const row of rows) {
    if (!keys.has(row.capability))
      problems.push(`delivery: dependency row ${row.capability} is not a known capability`);
    if (!phaseOrder.has(row.phase))
      problems.push(`delivery: ${row.capability} has phase "${row.phase}" not in phaseOrder`);
    for (const t of row.dependsOn ?? []) {
      if (!keys.has(t))
        problems.push(`delivery: ${row.capability} dependsOn unknown capability ${t}`);
      if (t === row.capability) problems.push(`delivery: ${row.capability} depends on itself`);
    }
    for (const t of row.parallelWith ?? []) {
      if (!keys.has(t))
        problems.push(`delivery: ${row.capability} parallelWith unknown capability ${t}`);
    }
  }
  // acyclic dependsOn graph (DFS with colours)
  const colour = new Map();
  const walk = (n, trail) => {
    colour.set(n, 1);
    for (const m of byCap.get(n)?.dependsOn ?? []) {
      const c = colour.get(m) ?? 0;
      if (c === 1) problems.push(`delivery: dependency cycle ${[...trail, n, m].join(" -> ")}`);
      else if (c === 0 && byCap.has(m)) walk(m, [...trail, n]);
    }
    colour.set(n, 2);
  };
  for (const row of rows) if (!colour.get(row.capability)) walk(row.capability, []);
  // transitive reachability for the required-dependency truths
  const reaches = (from, target, seen = new Set()) => {
    for (const t of byCap.get(from)?.dependsOn ?? []) {
      if (t === target) return true;
      if (!seen.has(t)) {
        seen.add(t);
        if (reaches(t, target, seen)) return true;
      }
    }
    return false;
  };
  for (const truth of delivery.requiredDependencyTruths ?? []) {
    if (!byCap.has(truth.from))
      problems.push(`delivery: required-truth source ${truth.from} is missing`);
    else if (!reaches(truth.from, truth.dependsOn))
      problems.push(
        `delivery: required dependency truth violated — "${truth.truth}" (${truth.from} must depend on ${truth.dependsOn})`
      );
  }
  for (const u of delivery.requiredUiPrecedence ?? []) {
    const row = byCap.get(u.capability);
    if (!row || row.mustPrecedeUi !== true)
      problems.push(`delivery: UI-precedence truth violated — "${u.truth}" (${u.capability})`);
  }
  return problems;
}

export function validate(repoRoot = REPO_ROOT) {
  const problems = [];
  const reg = loadRegistry(repoRoot);
  const statusVocab = new Set(reg.statusVocabulary);
  const decisionVocab = new Set(reg.decisionVocabulary);
  const envVocab = new Set(reg.environmentModelVocabulary);
  const onDisk = adrNumbersOnDisk(repoRoot);

  const matrixPath = path.join(repoRoot, MATRIX_REL);
  const matrixText = fs.existsSync(matrixPath) ? fs.readFileSync(matrixPath, "utf8") : "";
  const registerText = fs.readFileSync(
    path.join(repoRoot, "docs", "adr", "ACTION-REGISTER.md"),
    "utf8"
  );

  const routesText = readTextSafe(repoRoot, ROUTES_REL);
  const composeText = readTextSafe(repoRoot, COMPOSE_REL);
  const scripts = packageScripts(repoRoot);
  const adminRoutes = adminRouteSet(repoRoot);

  const problemsRowCell = (act) => new RegExp(`\\|\\s*${act}\\s*\\|`).test(registerText);

  const warnings = [];
  const seenKeys = new Set();
  const referencedActs = new Set();
  const referencedAdrs = new Set();

  for (const cap of reg.capabilities) {
    const id = cap.capability ?? "(missing key)";
    if (!cap.capability) problems.push("a capability row is missing its `capability` key");
    if (seenKeys.has(id)) problems.push(`duplicate capability key: ${id}`);
    seenKeys.add(id);

    // 1. status
    if (!statusVocab.has(cap.status))
      problems.push(`${id}: status "${cap.status}" not in controlled vocabulary`);
    // 2. decision
    if (!decisionVocab.has(cap.decision))
      problems.push(`${id}: decision "${cap.decision}" not in controlled vocabulary`);
    // 3. environment classification
    if (!envVocab.has(cap.environmentModel))
      problems.push(
        `${id}: environmentModel "${cap.environmentModel}" not in controlled vocabulary`
      );
    // 4. shared services carry isolation notes
    if (isShared(cap) && !hasIsolationNotes(cap))
      problems.push(`${id}: shared service must carry leakage/isolation notes`);
    // 5. production candidate has a local free path
    if (isProductionCandidate(cap) && !hasLocalFreePath(cap))
      problems.push(
        `${id}: production candidate must name a local free development path (got "${cap.localFreeCandidate}")`
      );
    // 6. delivered requires route or proof
    if (isDeliveredish(cap) && !hasRouteOrProof(cap))
      problems.push(
        `${id}: status "${cap.status}" requires a BFF/route contract or a proof/evidence reference`
      );
    // 7. ADR references resolve to files
    for (const m of `${cap.adr ?? ""}`.matchAll(/\bADR-(\d{4})\b/g)) {
      const n = Number(m[1]);
      if (!onDisk.has(n))
        problems.push(`${id}: references ADR-${m[1]} but docs/adr/ has no matching file`);
      else referencedAdrs.add(n);
    }
    // 8a. ADR-ACT present in register as a real table row + linked from matrix
    for (const m of `${cap.actionRegister ?? ""}`.matchAll(/\bADR-ACT-(\d{4})\b/g)) {
      const act = `ADR-ACT-${m[1]}`;
      referencedActs.add(act);
      if (!problemsRowCell(act))
        problems.push(
          `${id}: actionRegister ${act} is not present as a table row in ACTION-REGISTER.md`
        );
      if (matrixText && !matrixText.includes(act))
        problems.push(`${id}: actionRegister ${act} is not linked from the matrix markdown`);
    }
    // 8b. every capability appears in the matrix markdown
    if (matrixText && cap.capability && !matrixText.includes(cap.capability)) {
      problems.push(`${id}: capability key does not appear in the matrix markdown (run --render)`);
    }

    // 9. delivered/locally-proven proof references must resolve to a real package.json proof:* script.
    if (isDeliveredish(cap)) {
      for (const tok of proofTokens(cap.proof)) {
        if (!scripts[tok])
          problems.push(`${id}: proof reference "${tok}" has no matching package.json script`);
      }
    }
    // 10. delivered/locally-proven /api routes must exist in the BFF route table.
    if (isDeliveredish(cap) && routesText) {
      for (const tok of pathTokens(cap.bffContract, "/api/")) {
        if (!routesText.includes(tok))
          problems.push(`${id}: BFF contract claims route "${tok}" not found in ${ROUTES_REL}`);
      }
    }
    // 11. delivered/locally-proven /admin UI routes must exist as a route file.
    if (isDeliveredish(cap)) {
      for (const tok of pathTokens(cap.adminUi, "/admin/")) {
        if (!adminRoutes.has(tok))
          problems.push(
            `${id}: admin UI claims route "${tok}" with no matching route file under ${ADMIN_ROUTES_DIR_REL}`
          );
      }
    }
  }

  // 12. Delivery spine: phase assignment + dependency graph integrity (ADR-ACT-0252).
  for (const p of validateDelivery(reg.delivery, seenKeys)) problems.push(p);

  // 13. Mock/forbidden services must stay behind a Compose profile (never always-on / production).
  if (composeText) {
    for (const svc of FORBIDDEN_COMPOSE_SERVICES) {
      if (
        new RegExp(`^ {2}${svc}:\\s*$`, "m").test(composeText) &&
        !composeServiceIsGated(composeText, svc)
      )
        problems.push(
          `compose: forbidden-in-production service "${svc}" is not behind a Compose profile`
        );
    }
  }

  // 14-17. Phase-gate + dependency-consistency honesty checks (ADR-ACT-0253). These need capability
  // metadata (domain/decision/status) + ADR readiness, so they live here rather than in validateDelivery.
  const delivery = reg.delivery ?? {};
  const byCap = new Map((delivery.dependencies ?? []).map((d) => [d.capability, d]));
  const statusOf = new Map(reg.capabilities.map((c) => [c.capability, c.status]));
  const decisionOf = new Map(reg.capabilities.map((c) => [c.capability, c.decision]));
  const domainOf = new Map(reg.capabilities.map((c) => [c.capability, c.domain]));
  const reaches = (from, target, seen = new Set()) => {
    for (const t of byCap.get(from)?.dependsOn ?? []) {
      if (t === target) return true;
      if (!seen.has(t)) {
        seen.add(t);
        if (reaches(t, target, seen)) return true;
      }
    }
    return false;
  };

  // 14. Phase gates: a phase's planned capabilities may not advance to a delivered-ish status until
  //     its gating ADRs are Accepted / implementation-ready.
  for (const [phase, gate] of Object.entries(delivery.phaseGates ?? {})) {
    if (phase.startsWith("$")) continue;
    const required = gate.requiresAdrsReady ?? [];
    const notReady = required.filter((a) => !adrImplementationReady(repoRoot, a));
    const advanced = (delivery.dependencies ?? []).filter(
      (d) =>
        d.phase === phase &&
        d.track === "planned" &&
        ADVANCED_STATUSES.has(statusOf.get(d.capability))
    );
    if (advanced.length && notReady.length)
      problems.push(
        `delivery: ${phase} has advanced capabilities (${advanced
          .map((d) => d.capability)
          .join(
            ", "
          )}) but gating ADR(s) ${notReady.join(", ")} are not Accepted/implementation-ready`
      );
    else if (notReady.length)
      warnings.push(
        `${phase} is gated on ${required.join(", ")}; not yet ready: ${notReady.join(
          ", "
        )}. Implementation must not start until these are Accepted or implementation-ready.`
      );
  }

  // 15. Entitlement consistency: every billing/entitlement capability (except entitlements itself)
  //     must reference `entitlements` in the delivery graph.
  for (const cap of reg.capabilities) {
    if (
      domainOf.get(cap.capability) === "billing-entitlements" &&
      cap.capability !== "entitlements" &&
      byCap.has(cap.capability) &&
      !reaches(cap.capability, "entitlements")
    )
      problems.push(
        `delivery: entitlement-gated capability ${cap.capability} does not depend on \`entitlements\``
      );
  }

  // 16. Provider consistency: every compose/adapter capability must reference the service catalog.
  for (const cap of reg.capabilities) {
    if (
      ["compose", "adapter"].includes(decisionOf.get(cap.capability)) &&
      cap.capability !== "service-catalog-provider-model" &&
      byCap.has(cap.capability) &&
      !reaches(cap.capability, "service-catalog-provider-model")
    )
      problems.push(
        `delivery: provider-backed capability ${cap.capability} does not depend on \`service-catalog-provider-model\``
      );
  }

  // 17. Quota honesty: quota enforcement is Phase 2 — it must not be claimed delivered before then.
  if (isDeliveredish({ status: statusOf.get("quota-enforcement") }))
    problems.push(
      "delivery: quota-enforcement claims a delivered status, but quota enforcement is Phase 2 (only a Phase-1 hook is permitted)"
    );

  // Non-failing reports: ADR maturity. Separate not-yet-ready from implementation-ready.
  const refs = [...referencedAdrs].sort((a, b) => a - b).map((n) => String(n).padStart(4, "0"));
  const proposedNotReady = refs.filter(
    (n) =>
      /^proposed/i.test(adrStatus(repoRoot, n)) && !adrImplementationReady(repoRoot, `ADR-${n}`)
  );
  const ready = refs.filter((n) => adrImplementationReady(repoRoot, `ADR-${n}`));
  if (proposedNotReady.length)
    warnings.push(
      `${proposedNotReady.length} referenced ADR(s) are still Proposed and not implementation-ready: ${proposedNotReady
        .map((n) => `ADR-${n}`)
        .join(
          ", "
        )}. Capabilities behind these are not implementation-ready until the ADR is hardened.`
    );
  if (ready.length)
    warnings.push(
      `${ready.length} referenced ADR(s) are Accepted or implementation-ready: ${ready
        .map((n) => `ADR-${n}`)
        .join(", ")}.`
    );

  return {
    ok: problems.length === 0,
    problems,
    warnings,
    count: reg.capabilities.length,
    referencedActs: [...referencedActs].sort(),
  };
}

function esc(v) {
  return String(v ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

export function renderTables(repoRoot = REPO_ROOT) {
  const reg = loadRegistry(repoRoot);
  const byDomain = new Map();
  for (const d of reg.domains) byDomain.set(d, []);
  for (const cap of reg.capabilities) {
    if (!byDomain.has(cap.domain)) byDomain.set(cap.domain, []);
    byDomain.get(cap.domain).push(cap);
  }

  const out = [];
  out.push(
    `<!-- Generated from ${REGISTRY_REL} on ${reg.date}. ${reg.capabilities.length} capability rows. -->`
  );
  out.push("");
  for (const [domain, caps] of byDomain) {
    if (!caps.length) continue;
    out.push(`### ${DOMAIN_TITLES[domain] ?? domain}`);
    out.push("");
    // Decision table
    out.push(
      "| Capability | Status | Purpose | Compose / provider | Decision | Local free candidate | Environment model | Shared/per-env | Priority | Size | Risk |"
    );
    out.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
    for (const c of caps) {
      out.push(
        `| \`${esc(c.capability)}\` | ${esc(c.status)} | ${esc(c.purpose)} | ${esc(c.composeSupport)} | ${esc(c.decision)} | ${esc(c.localFreeCandidate)} | ${esc(c.environmentModel)} | ${esc(c.sharedPerEnv)} | ${esc(c.priority)} | ${esc(c.size)} | ${esc(c.risk)} |`
      );
    }
    out.push("");
    // Governance / isolation table
    out.push(
      "| Capability | Tenant isolation | Data isolation | Permission | Audit events | Readiness model | BFF contract | Admin UI | Self-service UI | Proof | Production blockers | ADR | ADR-ACT | Notes |"
    );
    out.push(
      "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
    );
    for (const c of caps) {
      out.push(
        `| \`${esc(c.capability)}\` | ${esc(c.tenantIsolation)} | ${esc(c.dataIsolation)} | ${esc(c.permissionModel)} | ${esc(c.auditEvents)} | ${esc(c.readinessModel)} | ${esc(c.bffContract)} | ${esc(c.adminUi)} | ${esc(c.selfServiceUi)} | ${esc(c.proof)} | ${esc(c.productionBlockers)} | ${esc(c.adr)} | ${esc(c.actionRegister)} | ${esc(c.notes)} |`
      );
    }
    out.push("");
  }
  return out.join("\n");
}

export function render(repoRoot = REPO_ROOT) {
  const matrixPath = path.join(repoRoot, MATRIX_REL);
  const text = fs.readFileSync(matrixPath, "utf8");
  const startIdx = text.indexOf(TABLE_START);
  const endIdx = text.indexOf(TABLE_END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`matrix markdown is missing the ${TABLE_START} / ${TABLE_END} markers`);
  }
  const before = text.slice(0, startIdx + TABLE_START.length);
  const after = text.slice(endIdx);
  const next = `${before}\n\n${renderTables(repoRoot)}\n${after}`;
  fs.writeFileSync(matrixPath, next);
  return next;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const mode = process.argv[2];
  if (mode === "--render") {
    render();
    console.log("[validate-universal-foundation] rendered matrix tables from registry.");
  }
  const result = validate();
  for (const w of result.warnings ?? [])
    console.warn(`[validate-universal-foundation] warning: ${w}`);
  if (result.ok) {
    console.log(
      `[validate-universal-foundation] OK — ${result.count} capabilities; ADR-ACT linked: ${result.referencedActs.join(", ")}.`
    );
    process.exit(0);
  }
  console.error("[validate-universal-foundation] problems:");
  for (const p of result.problems) console.error(`  - ${p}`);
  process.exit(1);
}
