import { useQuery } from "@tanstack/react-query";
import { graphqlRequest } from "@platform/graphql-browser-client";
// Generated by `npm run codegen` from packages/contracts-graphql/src/operations/widget.graphql.
// This import is the ONLY way feature code references an operation — never inline strings.
import { WidgetListDocument } from "@platform/contracts-graphql";

export const widgetListQueryKey = ["widget", "list"] as const;

/**
 * Read hook. The hook layer is the single boundary that talks to the GraphQL
 * client: it passes a generated TypedDocumentNode and returns plain data, so the
 * page/components stay dumb and free of GraphQL.
 */
export function useWidgetList() {
  return useQuery({
    queryKey: widgetListQueryKey,
    queryFn: async () => {
      const data = await graphqlRequest(WidgetListDocument);
      return data.widgets;
    },
    staleTime: 30_000,
    retry: false,
  });
}
