// ---------------------------------------------------------------------------
// Proof-ladder registry — the single source of truth for the repeatable local
// runtime proofs (`npm run proof:*`). Consumed by the /admin/platform cockpit
// (read-only index card), referenced by README/evidence, and reconciled against
// package.json scripts by a unit test (proof-registry.test.ts in platform-api).
//
// Add new proofs HERE (plus the package.json script + README mention); never
// hand-duplicate this list in UI components or docs tooling.
// ---------------------------------------------------------------------------

export const PROOF_LADDER = [
  "proof:auth-settings",
  "proof:auth-idps",
  "proof:auth-credential-lifecycle",
  "proof:auth-oidc-enterprise",
  "proof:email-sender",
  "proof:tenant-domains",
  "proof:tenant-storage",
  "proof:tenant-observability",
  "proof:webhooks",
  "proof:webhook-worker",
  "proof:tenant-domains-routing",
  "proof:webhook-redrive",
  "proof:platform-services",
  "proof:backup-local",
  "proof:backup-control-route",
  "proof:domain-identity-matrix",
  "proof:tenant-custom-domain-resolution",
  "proof:tenant-domain-canonical",
  "proof:tenant-custom-domain-auth-origin",
  "proof:service-clickthrough-policy",
  "proof:tenant-domain-claim-lifecycle",
  "proof:tenant-lifecycle",
  "proof:billing-provider",
  "proof:billing-readiness-route",
  "proof:billing-control-route",
  "proof:billing-catalog",
  "proof:compliance-report-route",
  "proof:http-engine-providers",
  "proof:lago-billing-provider",
  "proof:l4-substrate-closure",
  "proof:l5-compose-local-resilience-closure",
  "proof:l5-identity-access-resilience",
  "proof:l5-postgres-tenant-identity-resilience",
  "proof:l5-staging-resilience-certification",
  "proof:l6-foundation-journey",
  "proof:l6-prod-shaped-certification",
  "proof:temporal-workflow-provider",
  "proof:windmill-automation-provider",
  "proof:workflow-adapters",
  "proof:workflow-closure",
  "proof:workflow-provider-live",
  "proof:workflow-control-route",
  "proof:workflow-readiness-route",
  "proof:provider-binding-report-route",
  "proof:support-approval",
  "proof:workflow-engine",
  "proof:approval-workflow",
  "proof:observability-control-route",
  "proof:observability-readiness-route",
  "proof:observability-provider-closure",
  "proof:observability-metrics-traces-closure",
  "proof:provider-observability-closure",
  "proof:provider-observability-contract",
  "proof:full-observability-contract",
  "proof:alert-incident-closure",
  "proof:object-scan-closure",
  "proof:pitr-restore-drill",
  "proof:data-residency",
  "proof:data-governance",
  "proof:data-portability",
  "proof:security-control-route",
  "proof:composed-provider-runtime-closure",
  "proof:entitlements",
  "proof:entitlement-policy-chain",
  "proof:service-catalog-registry",
  "proof:entitlements-postgres",
  "proof:entitlements-routes",
  "proof:delegated-admin",
  "proof:metering",
  "proof:quota-enforcement",
  "proof:metering-quota-routes",
  "proof:api-keys",
  "proof:rate-limits",
  "proof:rate-limits-redis",
  "proof:provider-environment-classification",
  "proof:api-key-routes",
  "proof:route-contracts",
  "proof:search",
  "proof:search-isolation",
  "proof:search-routes",
  "proof:event-bus",
  "proof:event-worker",
  "proof:event-redrive",
  "proof:profile-self-service",
  "proof:notification-preferences",
  "proof:notification-dispatch",
  "proof:observability-signals",
  "proof:alerting",
  "proof:incident-foundation",
  "proof:alert-notification-bridge",
  "proof:scheduled-jobs",
  "proof:scheduled-job-routes",
  "proof:secret-store-contract",
  "proof:secrets-openbao",
  "proof:provider-secrets-readiness",
  "proof:provider-config",
  "proof:provider-readiness-contract",
  "proof:composed-provider-readiness",
  "proof:history",
  "proof:notification-email-transport",
  "proof:notification-webhook-transport",
  "proof:notification-transport-routes",
  "proof:environment-registry",
  "proof:environment-operations",
  "proof:environment-admin-bootstrap",
  "proof:clickthrough",
  "proof:dashboards",
  "proof:metrics-prometheus",
  "proof:typed-secret-resolution",
  "proof:in-memory-automation-runner",
  "proof:in-memory-billing-catalog",
  "proof:in-memory-provider-runtime",
  "proof:in-memory-vs-real-parity",
  "proof:ui-semantic-groups",
  "proof:ui-semantic-sub-organisations",
  "proof:ui-semantic-claim-mapping",
  "proof:tenant-storage-objects",
] as const;

export type ProofLadderEntry = (typeof PROOF_LADDER)[number];
